name: Test suite

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          /tmp/tlpkg
          ~/.texlive
        key: texlive-2021

    - name: Set up TeX Live environment
      uses: pgf-tikz/actions/install-tl@master
      with:
        packages:
          amsfonts
          amsmath
          atbegshi
          atveryend
          bigintcalc
          bitset
          colortbl
          courier
          ctablestack
          dvipdfmx
          dvips
          dvisvgm
          ec
          epstopdf-pkg
          etexcmds
          fp
          geometry
          gettitlestring
          graphics
          graphics-def
          hycolor
          hyperref
          iftex
          imakeidx
          intcalc
          kvdefinekeys
          kvoptions
          kvsetkeys
          l3build
          latex
          latex-bin
          letltxmacro
          listings
          lm
          ltxcmds
          luainputenc
          luaotfload
          luatex
          luatexbase
          luaxml
          make4ht
          makeindex
          metafont
          mfware
          ms
          oberdiek
          pdfescape
          pdftexcmds
          psnfss
          refcount
          rerunfilecheck
          stringenc
          symbol
          tex4ht
          texlive-scripts
          times
          todonotes
          tools
          uniquecounter
          url
          xcolor
          xetex
          xkeyval
          zapfding

    - name: Install PGF
      run: |
        tlmgr init-usertree --usertree $PWD
        echo "TEXMFHOME=$PWD" >> $GITHUB_ENV

    - name: Generate the revision file
      run: |
        l3build revisionfile
        cat tex/generic/pgf/pgf.revision.tex
        echo "GIT_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

    - name: Run test suite
      run: |
        l3build check -q -H --show-log-on-error
