name: Manual

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install PGF
      run: |
        tlmgr init-usertree --usertree $PWD
        echo "TEXMFHOME=$PWD" >> $GITHUB_ENV

    - name: Generate the revision file
      run: |
        l3build revisionfile
        cat tex/generic/pgf/pgf.revision.tex
        echo "GIT_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

    - name: Build the manual
      run: |
        l3build doc -q -H

    - uses: actions/upload-artifact@v2
      with:
        name: pgfmanual
        path: build/doc/pgfmanual.pdf

    - name: Deploy tlcontrib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update -qq
        apt-get install -qq libxml-parser-perl libxml-xpath-perl libtext-unidecode-perl tree
        cp build/doc/pgfmanual.pdf ../
        bash ci/update_tlcontrib.sh
